### PR TITLE
Define as module

### PR DESCRIPTION
**Pull request by orangejenny**
Was having trouble using this in conjunction with RequireJS's optimizer.

### CODE REVIEW

**Comment by alexandernst** [comment]
Clean patch, as last time, I like it.
Just one question: this doesn't affect how the plugin works without external loaders, right?

**Comment by orangejenny** [comment]
Yep, the last `else` takes care of environments where there aren't external loaders.

**Comment by alexandernst** [comment]
Great, excellent work!

**Comment by orangejenny** [comment]
Thanks for the quick turnaround!

**Comment by orangejenny** [comment]
Hi, would you mind making a tag/release that includes this change?

**Comment by alexandernst** [comment]
Done! :)

**Comment by orangejenny** [comment]
sweet, thanks!

**Pull request merged**
