### PR TITLE
Extract node_id from obj if needed

### PR DESCRIPTION
**Pull request by orangejenny**
JSTree can pass either a node id or an object to `redraw_node`. This can cause cases where actions don't appear, because an action was added to `actions` using an id string, but later code tries to access it with the object version of the same node.

### CODE REVIEW

**Review by alexandernst — APPROVED** [review]
Nice and clean

**Comment by alexandernst** [comment]
will release a new version in an hour or so

**Comment by orangejenny** [comment]
Sweet, that was quick. Thanks!

**Comment by alexandernst** [comment]
New version released! Thank you again :)

**Pull request merged**
